apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-secret
  namespace: app
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: ghcr-secret
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"ghcr.io":{"username":"{{ .username }}","password":"{{ .password }}","auth":"{{ printf "%s:%s" .username .password | b64enc }}"}}}
  data:
  - secretKey: username
    remoteRef:
      key: todo-api/github-credentials
      property: username
  - secretKey: password
    remoteRef:
      key: todo-api/github-credentials
      property: password

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: metrics-secret
  namespace: app
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: metrics-secret
  data:
  - secretKey: api-key
    remoteRef:
      key: todo-api/metrics-api-key
      property: api-key

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-repo-secret
  namespace: argocd
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: production-ready-devops-repo
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: https://github.com/Stefanie-A/production-ready-devops-project.git
  data:
  - secretKey: username
    remoteRef:
      key: todo-api/github-credentials
      property: username
  - secretKey: password
    remoteRef:
      key: todo-api/github-credentials
      property: password