apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-api
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: todo-api=ghcr.io/stefanie-a/todo-api
    argocd-image-updater.argoproj.io/todo-api.allow-tags: regexp:^([a-f0-9]{7})$
    argocd-image-updater.argoproj.io/todo-api.update-strategy: newest-build
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    repoURL: 'https://github.com/Stefanie-A/production-ready-devops-project.git'
    targetRevision: HEAD
    path: k8s/manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    syncOptions:
      # Ensure the ArgoCD service account has permissions to create namespaces, or syncs may fail.
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true